/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_ROBOT_STATE_PB_H_INCLUDED
#define PB_ROBOT_STATE_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _SensorSnapshot {
    float temp;
    float hum;
    float dist_rear;
    float dist_left;
    float dist_right;
    int32_t gas;
    int32_t enc_fl;
    int32_t enc_fr;
    int32_t enc_rl;
    int32_t enc_rr;
} SensorSnapshot;

typedef struct _MotorCommand {
    float linear_vel;
    float angular_vel;
} MotorCommand;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define SensorSnapshot_init_default              {0, 0, 0, 0, 0, 0, 0, 0, 0, 0}
#define MotorCommand_init_default                {0, 0}
#define SensorSnapshot_init_zero                 {0, 0, 0, 0, 0, 0, 0, 0, 0, 0}
#define MotorCommand_init_zero                   {0, 0}

/* Field tags (for use in manual encoding/decoding) */
#define SensorSnapshot_temp_tag                  1
#define SensorSnapshot_hum_tag                   2
#define SensorSnapshot_dist_rear_tag             3
#define SensorSnapshot_dist_left_tag             4
#define SensorSnapshot_dist_right_tag            5
#define SensorSnapshot_gas_tag                   6
#define SensorSnapshot_enc_fl_tag                7
#define SensorSnapshot_enc_fr_tag                8
#define SensorSnapshot_enc_rl_tag                9
#define SensorSnapshot_enc_rr_tag                10
#define MotorCommand_linear_vel_tag              1
#define MotorCommand_angular_vel_tag             2

/* Struct field encoding specification for nanopb */
#define SensorSnapshot_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, FLOAT,    temp,              1) \
X(a, STATIC,   SINGULAR, FLOAT,    hum,               2) \
X(a, STATIC,   SINGULAR, FLOAT,    dist_rear,         3) \
X(a, STATIC,   SINGULAR, FLOAT,    dist_left,         4) \
X(a, STATIC,   SINGULAR, FLOAT,    dist_right,        5) \
X(a, STATIC,   SINGULAR, INT32,    gas,               6) \
X(a, STATIC,   SINGULAR, INT32,    enc_fl,            7) \
X(a, STATIC,   SINGULAR, INT32,    enc_fr,            8) \
X(a, STATIC,   SINGULAR, INT32,    enc_rl,            9) \
X(a, STATIC,   SINGULAR, INT32,    enc_rr,           10)
#define SensorSnapshot_CALLBACK NULL
#define SensorSnapshot_DEFAULT NULL

#define MotorCommand_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, FLOAT,    linear_vel,        1) \
X(a, STATIC,   SINGULAR, FLOAT,    angular_vel,       2)
#define MotorCommand_CALLBACK NULL
#define MotorCommand_DEFAULT NULL

extern const pb_msgdesc_t SensorSnapshot_msg;
extern const pb_msgdesc_t MotorCommand_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define SensorSnapshot_fields &SensorSnapshot_msg
#define MotorCommand_fields &MotorCommand_msg

/* Maximum encoded size of messages (where known) */
#define MotorCommand_size                        10
#define ROBOT_STATE_PB_H_MAX_SIZE                SensorSnapshot_size
#define SensorSnapshot_size                      80

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
