/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.1 */

#include "robot_state.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(SensorSnapshot, SensorSnapshot, AUTO)


PB_BIND(MotorCommand, MotorCommand, AUTO)



